<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Permafrost</AssemblyName>
    <RootNamespace>Permafrost</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
    <Product>Permafrost</Product>
    <Title>Permafrost</Title>
    <LangVersion>latest</LangVersion>
    <Version>0.4.3.0</Version>
    <AssemblyVersion>0.4.3.0</AssemblyVersion>
    <FileVersion>0.4.3.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>
</Project>
